[buildPlans.IosevkaCharon]
family = "Iosevka Charon"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
buildTextureFeature = true
noLigation = true

[buildPlans.IosevkaCharon.variants]
inherits = "ss08"

[buildPlans.IosevkaCharon.variants.design]
two = "straight-neck-serifless"
three = "two-arcs"
five = "oblique-flat-serifless"
six = "open-contour"
eight = "crossing"
nine = "open-contour"
zero = "oval-slashed"
capital-q = "crossing"
d = "tailed-serifless"
e = "rounded"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
u = "tailed-serifless"
v = "curly-serifless"
w = "curly-serifless"
y = "curly-turn-serifless"
ampersand = "closed"
at = "fourfold"
dollar = "through"

[buildPlans.IosevkaCharon.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCharon.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCharon.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaCharonMono]
family = "Iosevka Charon Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
buildTextureFeature = true
noLigation = true

[buildPlans.IosevkaCharonMono.variants]
inherits = "ss08"

[buildPlans.IosevkaCharonMono.variants.design]
two = "straight-neck-serifless"
three = "two-arcs"
five = "oblique-flat-serifless"
six = "open-contour"
eight = "crossing"
nine = "open-contour"
zero = "oval-slashed"
capital-q = "crossing"
d = "tailed-serifless"
e = "rounded"
i = "serifed-flat-tailed"
j = "serifed"
l = "serifed-flat-tailed"
u = "tailed-serifless"
v = "curly-serifless"
w = "curly-serifless"
y = "curly-turn-serifless"
ampersand = "closed"
at = "fourfold"
dollar = "through"

[buildPlans.IosevkaCharonMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCharonMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCharonMono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
